### ISSUE TITLE
primevue 3.48.1

### ISSUE THREAD

**Issue by amonga67** [primefaces/sakai-vue#24]
Hi ,
very good starter !
Layout breaks on primevue 3.48.1 , will it be supported soon ? 
Thank you

**Comment by jonaskahn** [comment]
it's actually broken since 3.47.x. I'm fallback to 3.46 vesion

**Comment by adamczykpiotr** [comment]
@tugcekucukoglu Could we get some help with this or at least get comprehensive changes between each version so anyone can make a PR themselves?

**Comment by inane** [comment]
How are they fixing the problem with the most recent primevue versions?

**Comment by adamczykpiotr** [comment]
> @tugcekucukoglu Could we get some help with this or at least get comprehensive changes between each version so anyone can make a PR themselves?

@cagataycivici @primefaces Up! Is this issue actively worked on? If not, i'd love to help you with migration if you could provide detailed changelog between 3.46 and current version

**Comment by ernest-folch-fleksy** [comment]
Seems it also breaks using 3.49.1

**Comment by adamczykpiotr** [comment]
A new Sakai-Vue release 3.10 has been published: https://github.com/primefaces/sakai-vue/releases/tag/3.10.0 which is based on PrimeVue 3.49.1

@amonga67 you can close the issue ;)

**Comment by tugcekucukoglu** [comment]
Version 4.0.0. is released. But older versions are available :https://github.com/primefaces/sakai-vue/releases
