### ISSUE TITLE
services cannot work

### ISSUE THREAD

**Issue by Yootthanaboon** [primefaces/sakai-vue#28]
<img width="1673" alt="Screenshot 2567-03-28 at 21 07 13" src="https://github.com/primefaces/sakai-vue/assets/159749002/29575b65-a177-416b-9835-6adb17abc500">

https://sakai.primevue.org/uikit/table

**Comment by tugcekucukoglu** [comment]
I was fixed. https://sakai.primevue.org/uikit/table

Thanks for your attention.
