### ISSUE TITLE
Is the topbar have dropdown ?

### ISSUE THREAD

**Issue by mzcoder-hub** [primefaces/sakai-vue#29]
its just a simple question cause i recon theres no dropdown in the topbar menu is it true ?

**Comment by gtim04** [comment]
Hello you can actually use overlay menus and integrate it on the topbar.

It was showcased here: https://sakai.primevue.org/uikit/menu

You can also explore the menu components you want to use here: https://v3.primevue.org/menu/

**Comment by tugcekucukoglu** [comment]
You could find Select demo here: https://sakai.primevue.org/uikit/input
