### ISSUE TITLE
PrimeVue 4.X.X

### ISSUE THREAD

**Issue by gtim04** [primefaces/sakai-vue#30]
Hello,

Can't ask for any better starter.

Layout breaks at PrimeVue 4 as there are unrecognized components anymore.

Will there be future updates for this Templates?

Thank you so much.

**Comment by j0rgedev** [comment]
I read that once v4 gets stable, all templates will be migrated, but I don't know if sakai will be updated since it is free. Check here:
https://github.com/orgs/primefaces/discussions/1604

**Comment by Lina-SHU** [comment]
Dears,

PrimeVue 4.0.0 has already released a stable version.
I would appreciate it if the template could be updated to the latest version.

Thank you so much!!

**Comment by j0rgedev** [comment]
@Lina-SHU  I don't think they'll be updating the template soon. Some styles like 'p-link' are not available in v4. I tried to update sakai to v4 but lot of things were missing.

**Comment by gtim04** [comment]
> I read that once v4 gets stable, all templates will be migrated, but I don't know if sakai will be updated since it is free. Check here: https://github.com/orgs/primefaces/discussions/1604

I see. Hoping that this template would get updated. Thank you.

**Comment by inane** [comment]
What should it be the best way to migrate as sakai's user to v.4-x-x ?

**Comment by gtim04** [comment]
Thank you so much all for updating this wonderful Layout!
