### ISSUE TITLE
Update to PrimeVue v4 failed

### ISSUE THREAD

**Issue by kurkoc** [primefaces/sakai-vue#31]
first of all; thank you for this great job.

after the update you have made, I am pulling the master branch, but I encounter some problems in the layout.  for better understanding, I will try to attach a screenshot.

![image](https://github.com/user-attachments/assets/3b40a44a-bef3-406d-838c-0f398d8b7679)

**Comment by j0rgedev** [comment]
@kurkoc it may be ready next week. It's already the weekend, so let's all just be waiting. Btw, I need to admit that they should've created a v4 migration branch instead of pushing it to the master one haha

**Comment by tugcekucukoglu** [comment]
Version 4.0.0 is relased. The latest updates can be checked.
