### ISSUE TITLE
Page load problem in version 4.0.0

### ISSUE THREAD

**Issue by kurkoc** [primefaces/sakai-vue#33]
i am looking at version 4.0.0, looks great but I would like to point out a problem.

when I try to go to some pages via the menu on the left, the page becomes unresponsive for a moment, but this does not always happen. and then,  when I try a second time it usually goes that page. even stranger, sometimes after page unresponsiveness, the screen refreshes itself. seems to be a problem with installing dependencies on demand on vite

**Comment by cagataycivici** [comment]
Seems to be vite related, added;

```js
 optimizeDeps: {
     noDiscovery: true
 },
```
