### ISSUE TITLE
[Question] How to set dark mode activate by default?

### ISSUE THREAD

**Issue by jonaskahn** [primefaces/sakai-vue#34]
Straight forward to my question, I want to setup darkmode is on by default. I already made it in V3 but in V4, the code changed a lot. Could developers help me? Thank you.

**Comment by jonaskahn** [comment]
Solved

**Comment by bilal-the-dev** [comment]
you didnt tell how to?

**Comment by jonaskahn** [comment]
Oh, sorry. I thought I was the only one.
I added the line `document.documentElement.classList.toggle('app-dark');` in `App.vue` 
```javascript
onBeforeMount(() => {
    document.documentElement.classList.toggle('app-dark');
});
```
If it does not work, change to `onMounted()`.


---
Btw, I made an enhance version of  sakai. [enhanced-sakai](https://github.com/jonaskahn/enhanced-sakai-vue)
There is a feature that the app configuration stores setting to the local storage, therefore we can keep the theme settings even F5 hit.

**Comment by bilal-the-dev** [comment]
cool, its working , do you know when we change the default settings of this sakai vue , it does not work i want to change the default setting, right now primary color is always emrald, i want to change that into` noir` ,and also want to change the surface to` gray.`
any way
Thanks
