### ISSUE TITLE
Invalid Prop in FloatingConfigurator.vue

### ISSUE THREAD

**Issue by HenriqueMoroziniHupp** [primefaces/sakai-vue#35]
Every time I access the Login page, "[Vue warn]: Invalid prop" appears in the console, the warning occurs on the toggle button dark mode within the `FloatingConfigurator.vue` component.

Expects a string with the icon value, but is receiving an object

Error: 
![Captura de tela de 2024-08-03 02-04-27](https://github.com/user-attachments/assets/c29fc915-f671-4278-bd24-6a8e4e1f692e)

---

Currently:
```vue
<Button :icon="{ 'pi pi-moon': isDarkTheme, 'pi pi-sun': !isDarkTheme }"  />
```

My sugestion:
```vue
<Button :icon="isDarkTheme ? 'pi pi-moon' : 'pi pi-sun'"  />
```

**Comment by jonaskahn** [comment]
Team already fixed this problem in the Main App. This is the code that taken form the main app to fix this.
```
        <button class="layout-topbar-action" type="button" @click="toggleDarkMode">
            <i :class="['pi', { 'pi-moon': isDarkTheme, 'pi-sun': !isDarkTheme }]"></i>
        </button>
```
I feel concern about the code quality, it's wired!!!

**Comment by cagataycivici** [comment]
[Fixed](https://github.com/primefaces/sakai-vue/commit/411fecb51743212f3490eb29d3481739b267ef30) but better needs to be handled at PrimeVue button prop type, we'll do it in v4.0.6. This is not Sakai related.
