### ISSUE TITLE
@primevue/core/api

### ISSUE THREAD

**Issue by unlimitedspace** [primefaces/sakai-vue#36]
Hello,

@primevue/core/api missing somehow,
because of that FilterMatchMode, FilterOperator etc cannot be imported
below some error examples..

[plugin:vite:import-analysis] Failed to resolve import "@primevue/core/api" from "src/views/uikit/TableDoc.vue". Does the file exist?
....../sakai-vue-master/src/views/uikit/TableDoc.vue:4:50
17 |  import { CustomerService } from '@/service/CustomerService';
18 |  import { ProductService } from '@/service/ProductService';
19 |  import { FilterMatchMode, FilterOperator } from '@primevue/core/api';
   |                                                   ^
20 |  import { onBeforeMount, reactive, ref } from 'vue';

[plugin:vite:import-analysis] Failed to resolve import "@primevue/core/api" from "src/views/pages/Crud.vue". Does the file ...../sakai-vue-master/src/views/pages/Crud.vue:3:34
14 |  import __unplugin_components_0 from 'primevue/button';
15 |  import { ProductService } from '@/service/ProductService';
16 |  import { FilterMatchMode } from '@primevue/core/api';
   |                                   ^
17 |  import { useToast } from 'primevue/usetoast';
18 |  import { onMounted, ref } from 'vue';

**Comment by Kenneth-Multicase** [comment]
Had the same problem. The solution was to add this package:
pnpm i @primevue/core

**Comment by cagataycivici** [comment]
It should have been installed transitively, @mertsincan wdyt?

**Comment by lucaspmarra** [comment]
This still a thing, had to install @primevue/core

**Comment by byronogis** [comment]
Try add `shamefully-hoist=true` to your `.npmrc` file.

**Comment by tugcekucukoglu** [comment]
Please try to use the latest version. If the problem still persists, please reopen this issue.
