### ISSUE TITLE
PrimeVue 4.0 the component becomes larger

### ISSUE THREAD

**Issue by Zhy946644** [primefaces/sakai-vue#38]
PrimeVue 4.0 is incompatible with TailwindCSS, causing the size of components like Button and Select to change. Input and MultiSelect components become very tall, which does not match the examples provided for PrimeVue 4.0 components.

The Input and MultiSelect components on the [PrimeVue showcase page](https://sakai.primevue.org/uikit/input) are affected by the incompatibility with TailwindCSS, leading to size changes that do not align with the examples provided on the PrimeVue 4.0 components page.
![image](https://github.com/user-attachments/assets/dbfbecd5-aec5-4325-b3b0-20f0a1fddaf8)
![image](https://github.com/user-attachments/assets/70babed2-e405-48d1-ae21-60ba76c893ee)

But in https://primevue.org/multiselect/
![image](https://github.com/user-attachments/assets/c5f4b4d8-69bf-442f-9f17-7048f1e4dd60)

The height of components such as Input and MultiSelect has changed as well. When I disabled TailwindCSS, the component styles returned to normal.

Or how to adjust the configuration of TailwindCSS, I hope to inform me of the results (repair or not) as soon as possible, thank you!

**Comment by cagataycivici** [comment]
This is due to line height of Tailwind Preflight adding line-height to every thing, you can either disable preflight or just use it as it is.

https://tailwindcss.com/docs/preflight
