### ISSUE TITLE
Default Primary and Surface Colors

### ISSUE THREAD

**Issue by VitriolicH** [primefaces/sakai-vue#39]
hello,

I don't want the theme configurator component to be in my website, and I don't want to use the emerald and the surface to be the default color of the website.
how can I change the default theme to be for example (indigo, slate).

Thanks in advance.

**Comment by juandiab** [comment]
Hello!, 

I have the same issue, how did you fix it?

**Comment by braianpereira** [comment]
Hello,

@VitriolicH and @juandiab,

If you haven’t checked it yet, the [documentation on Theme Customization](https://primevue.org/theming/styled/#customization) provides helpful guidance.

They show how to use definePreset() to pass your own custom preset. This might be exactly what you need to address your issue.

Let me know if you need further clarification or assistance!

**Comment by juandiab** [comment]
Thank you for your response! I’ll read about it test it!Great themes by the way! I’ve already convinced one of my friends to buy diamond-vue for his website!Best regards,JPSent from my iPhoneOn Jan 19, 2025, at 9:11 PM, Bráian Pereira ***@***.***> wrote:﻿
Hello,
@VitriolicH and @juandiab,
If you haven’t checked it yet, the documentation on Theme Customization provides helpful guidance.
They show how to use definePreset() to pass your own custom preset. This might be exactly what you need to address your issue.
Let me know if you need further clarification or assistance!
