### ISSUE TITLE
Blank page when run npm run   preview

### ISSUE THREAD

**Issue by tianangthang7** [primefaces/sakai-vue#4]
After 
npm run dev 
and 
npm run build 
with no errors
but when I run 
npm run preview
I see nothing.

**Comment by bahadirsofuoglu** [comment]
You should remove or customize 'base' in vite.config.js. Customized baseurl added for deployment mode. But I think you don't need this. 

<img width="645" alt="Screen Shot 2022-12-28 at 14 05 18" src="https://user-images.githubusercontent.com/45143524/209802617-d992a24f-3e31-48ab-9ca4-ea8b58d4c8af.png">
