### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by xCodeSoul** [primefaces/sakai-vue#41]
Hello

everything is fine , one thing remaining RTL support

will be perfect template 

best regards

**Comment by IncreMan** [comment]
I have decided to help community with self-made CSS file for RTL.
As a bonus I have added scrollbar design that uses template's variables.
[https://stackoverflow.com/questions/78989814/rtl-scrollbar-css-for-sakai-primevue-free-template/](https://stackoverflow.com/questions/78989814/rtl-scrollbar-css-for-sakai-primevue-free-template/)

**Comment by tugcekucukoglu** [comment]
We will consider it. Thank you.
