### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by IceflowRE** [primefaces/sakai-vue#42]
https://github.com/primefaces/sakai-vue/blob/411fecb51743212f3490eb29d3481739b267ef30/src/layout/composables/layout.js#L14-L15

Is not used anywhere.

(not gonna open a separate issue for the next one)

https://github.com/primefaces/sakai-vue/blob/411fecb51743212f3490eb29d3481739b267ef30/src/layout/AppMenuItem.vue#L79-L83

Line 82 can be removed as it is always false. You check above `!items.items` and then if `items.items`.

**Comment by tugcekucukoglu** [comment]
We will take a look. Thank you.
