### ISSUE TITLE
sass Deprecation Warning

### ISSUE THREAD

**Issue by sabri-ayadi** [primefaces/sakai-vue#53]
a issue about sass layout happen after building and running npm dev:

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
More info: https://sass-lang.com/d/legacy-js-api
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
  ╷
2 │ @import '@/assets/layout/layout.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    src/assets/styles.scss 2:9  root stylesheet

Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import

  ╷
4 │ @import '@/assets/demo/demo.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    src/assets/styles.scss 4:9  root stylesheet

Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ @import './variables/_common';
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
    src/assets/layout/layout.scss 1:9  @import
    src/assets/styles.scss 2:9         root stylesheet

Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import

  ╷
2 │ @import './variables/_light';
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
    src/assets/layout/layout.scss 2:9  @import
    src/assets/styles.scss 2:9         root stylesheet

Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import

  ╷
3 │ @import './variables/_dark';
  │         ^^^^^^^^^^^^^^^^^^^
  ╵
    src/assets/layout/layout.scss 3:9  @import
    src/assets/styles.scss 2:9         root stylesheet

Warning: 11 repetitive deprecation warnings omitted.
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
More info: https://sass-lang.com/d/legacy-js-api
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
More info: https://sass-lang.com/d/legacy-js-api
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
More info: https://sass-lang.com/d/legacy-js-api

who have idea about how to fix the dependency of sass ?

**Comment by martinspudich** [comment]
It happened to me when I migrated the project from PrimeVue V3 to V4.

I ended up replacing the /src/assets directory with the new one from the Sakai Vue project. Sass changed `@import` to `@use` in the Sass files."

**Comment by martinspudich** [comment]
Now I'm trying to resolve another issue:

`
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
`

**Comment by tugcekucukoglu** [comment]
They are fixed. Thank you.
