### ISSUE TITLE
Uncaught (in promise) Error: No PrimeVue Toast provided!

### ISSUE THREAD

**Issue by alphayowakarindi** [primefaces/sakai-vue#9]
I'm adding the template to an existing project and everything works fine. However, when I add the `Crud page` I get the error `Uncaught (in promise) Error: No PrimeVue Toast provided!`.

I tried to move the `Not Found page` and that worked. Kindly assist.

**Comment by tugcekucukoglu** [comment]
ToastService must be imported in main.js file

```
import ToastService from 'primevue/toastservice';

const app = createApp(App);
app.use(ToastService);
```
